# Time-lapse with Raspberry Pi controlled camera - Configuration file
# VER 8.0 for Python 3.12+
# Copyright (C) 2016- Istvan Z. Kovacs
#
# The configuration file is in YAML format and contains five 'documents' separated by '---'.
# Each document contains a section of the configuration parameters as described below.
# The configuration file is read in rpiconfig.py and the parameters are stored in dictionaries:
# mainConfig, timerConfig, camConfig, dirConfig, dbxConfig and rcConfig.
# The name of this configuration file is set in rpiconfig.py in the YAMLCFG_FILE variable.
# See the comments below for description of each parameter.

# Main configuration parameters.
# Loaded in rpiconfig.

# All internet use (Dropbox, ThingSpeak, Webssockect)
INTERNETUSE:  yes
# Local USB storage (instead of SD card) - not implemented yet!
LOCUSBUSE:    no

## Camera capture 'back-end' to use & configurations
# NOTE: When none of the below is selected, then
# fswebcam -d /dev/video0 
# is attemped to be used to capture an image
# FAKESNAP generates an empty file
FAKESNAPP:     no
# The use of picamera (v1) API is depracated since 2022! Use picamera2 (v2) instead!
# See https://picamera.readthedocs.io/en/release-1.13/api_camera.html
# RPICAM2 is using the Picamera2 API and is the preferred/recommended
# See https://datasheets.raspberrypi.com/camera/picamera2-manual.pdf
RPICAM2:      yes
# LIBCAMERA is using the rpicam-still (from rpicam-apps installed with picamera2) since 2022 
# See https://www.raspberrypi.com/documentation/computers/camera_software.html#rpicam-still
LIBCAMERA:    no

---
# Datetime periods configuration. 
# Loaded into timerConfig.

# The date period for activating the camera jobs. The dates are in YYYY-MM-DD format.
start_date: '2025-01-01'
stop_date:  '2025-12-31'
# Main time periods configuration during each day. The times are in HH:MM:SS format.
start_times: ['00:00:00', '08:00:00', '20:00:00']
stop_times:  ['07:59:59', '19:59:59', '23:59:59']
# Dark time start and stop times indeces, indicating times from the start_times and stop_times.
# If any of them is set -1 and if lat_lon is configured in the camConfig section below,
# the dark time period is auto-determined with pyephem based on the lat & lon camera location,
# else dark time period is not used.
start_dark_time: -1
stop_dark_time: -1
# Main timer execution interval configuration in seconds for all time periods above.
interval_sec: 10

---
# Camera configurations.
# Loaded into camConfig.

cam_id: 'CAM1'
lat_lon: ['57:04:39.4', '09:54:42.6']
cam_version: 'ov5647'
cam_type: 'noir' # 'daylight' or 'noir'
rec_type: 'still'
image_rot: 180
image_res: [1024, 768]
# Image capture intervals configuration in seconds for each time period above.
interval_sec: [30, 60, 30]
jpg_qual: 85
use_ovltxt: yes
use_irl: yes
bcm_irlport: 19
use_pir: no
bcm_pirport: 16
pirtd_sec: 15
# If use_dynctrl is yes, the camera controls in cam_expday, cam_expnight-irl and cam_expnight
# for each image are read from cam_controls.json file and applied based on time of day and IRL usage status.
use_dynctrl: yes
# Camera controls. See Apendix C in Picamera2 API documentation. 
# The control groups are selected in the code based on time of day and IRL usage status.
# The parameters under each group are applied in the order listed here!
cam_expday:
  AwbEnable: True  # Turn AWB algorithm on and off
  AwbMode:  'Daylight' # controls.AwbModeEnum.Auto, Tungsten, Fluorescent, Incandescent, Indoor, Daylight, Cloudy
  AeEnable: True   # Turn AEC/AGC algorithm on and off
  AeExposureMode: 'Normal' # controls.AeExposureModeEnum.Normal, Short, Long
  ExposureValue: 0 # EV compensation value. Floating point number between -8.0 and 8.0
  Contrast: 1.0    # Floating point number from 0.0, 1.0 to 32.0
  Brightness: 0.0  # Floating point number from -1.0 to 1.0
cam_expnight-irl:
  AwbEnable: True  # Turn AWB algorithm on and off
  AwbMode:  'Auto' # controls.AwbModeEnum.Auto, Tungsten, Fluorescent, Incandescent, Indoor, Daylight, Cloudy
  AeEnable: False   # Turn AEC/AGC algorithm on and off
  AeExposureMode: 'Normal' # controls.AeExposureModeEnum.Normal, Short, Long
  ExposureValue: 8.0 # EV compensation value. Floating point number between -8.0 and 8.0
  ExposureTime: 400000 # Exposure time for the sensor to use, measured in microseconds
  Contrast:  4.0   # Floating point number from 0.0, 1.0 to 32.0
  Brightness: 0.5  # Floating point number from -1.0 to 1.0
cam_expnight:
  AwbEnable: True  # Turn AWB algorithm on and off
  AwbMode:  'Auto' # controls.AwbModeEnum.Auto, Tungsten, Fluorescent, Incandescent, Indoor, Daylight, Cloudy
  AeEnable: False  # Turn AEC/AGC algorithm on and off
  AeExposureMode: 'Normal' # controls.AeExposureModeEnum.Normal, Short, Long
  ExposureValue: 3.0 # EV compensation value. Floating point number between -8.0 and 8.0
  ExposureTime: 10000000 # Exposure time for the sensor to use, measured in microseconds
  Contrast: 3.0    # Floating point number from 0.0, 1.0 to 32.0
  Brightness: 1.0  # Floating point number from -1.0 to 1.0

---
# Directory configuration for saving images locally.
# Loaded into dirConfig.

# The captured images are stored locally in a sub-folder with the current date `DDMMYY` as name, under the image_dir folder.
image_dir: './webcam'
# The number of images to keep in the directory (last list_size images).
list_size: 10
# Images list/indexing execution interval configuration in seconds for each main time period above.
interval_sec: [30.3, 60.3, 30.3]

---
# Dropbox configuration for uploading images to a Dropbox App folder.
# Loaded into dbConfig.

# Requires App key and App secret from Dropbox developer account.
# Use scripts/dbauth.py to create the token file after creating the Dropbox App.
# If INTERNETUSE or DROPBOXUSE = False in rpiconfig.py, dropbox upload is disabled regadless of these settings.
# Token/authentication pkl file created with dbauth.py script.
# If token_file is empty '', dropbox upload is disabled.
token_file: 'tokens.pkl'
# The current/last captured image is always uploaded with the name image_snap when uploaded to Dropbox App folder.
# The captured images are uploaded to a sub-folder with the current date `DDMMYY` as name, under the image_dir folder, under Dropbox App folder.
# with the filename format 'DDMMYY-HHMMSS-<cam_id>.jpg' (cam_id from camConfig section above).
image_snap: 'cam.jpg'
image_dir: './webcam'
# Images upload execution interval configuration in seconds for each main time period above.
interval_sec: [61.3, 121.3, 61.3]

---
# Remote controls configuration for sending status info and receiving control commands.
# Loaded into rcConfig.
# NOTE: The  main timer interval_sec value is used as time period to send status messages and/or to check for remote control commands.

# The list of RC options for remote control commands.
# Currently supported  RC options:
#   'ts-status' (ThingSpeak upload status as REST feed) and 'ts-cmd' (ThingSpeak receive command on TalkBack REST feed)
#   'ws-status' (WebSockets send status msg) and 'ws-cmd' (WebSockets receive command msg)
# If rc_type is empty [], any upload and remote control is disabled.
rc_type: [] #['ts-status', 'ts-cmd'] 
# List of token/authentication txt files for 'ts-*' and 'ws-*' rc_type.
# If the list is empty or the entry in the list is empty '', any upload and remote control is disabled.
token_file: ['ts_tokens.txt', 'ws_tokens.txt'] 
# Timeout in seconds for Cmd mode (activated/deactivated via remote control options).
# When Cmd mode is activated, if no valid command is received within this time, Cmd mode is deactivated.
# Set to -1 to disable timeout (Cmd mode remains active until deactivated with command).
cmd_mode_timeout: 180


