# YAML
---
#timerConfig:
  start_year: 2022
  stop_year: 2022
  start_month: 1
  stop_month: 12
  start_day: 1
  stop_day: 31
  start_hour: [0]
  start_min: [1]
  stop_hour: [23] 
  stop_min: [55] 
  interval_sec: [150, 30]
  token_file: ''
--- 
#camImgConfig:
  image_dir: './webcam'
  image_id: 'CAM1'
  image_rot: 0
  use_irl: 1
  bcm_irlport: 19
  use_pir: 1
  bcm_pirport: 26
  pirtd_sec: 15
  dark_hours: [17, 8] 
  dark_mins: [0, 0]
  dark_loc: ['57.0774992' , '9.9117876']
  interval_sec: [10]
---
#dirImgConfig:
  list_size: 10
  interval_sec: [30.3]
---
#dbImgConfig:
  image_snap: 'cam.jpg'
  interval_sec: [60.5]
  token_file: 'token_key.txt'
