# YAML
---
#timerConfig:
  start_year: 2016
  stop_year: 2016
  start_month: 1
  stop_month: 2
  start_day: 1
  stop_day: 29
  start_hour: [0]
  start_min: [1]
  stop_hour: [23] 
  stop_min: [55] 
  interval_sec: [150, 30]
--- 
#camImgConfig:
  image_dir: './webcam'
  dark_hours: [17, 8] 
  dark_mins: [0, 0]
  interval_sec: [300]
---
#dirImgConfig:
  list_size: 10
  dircheck_sec:  [303.3]
---
#dbImgConfig:
  image_snap: 'cam.jpg'
  dbcheck_sec: [305.3]
