# YAML
---
#timerConfig:
  start_year: 2015
  stop_year: 2015
  start_month: 12
  stop_month: 12
  start_day: 1
  stop_day: 27
  start_hour: [6]
  start_min: [3]
  stop_hour: [22] 
  stop_min: [1] 
--- 
#camImgConfig:
  image_dir: './webcam'
  dark_hours: [16, 8] 
  dark_mins: [0, 0]
  interval_sec: [300]
---
#dirImgConfig:
  list_size: 10
  dircheck_sec:  [303.3]
---
#dbImgConfig:
  image_snap: 'cam.jpg'
  dbcheck_sec: [305.3]
